### ISSUE TITLE
deg(R) = d => R = 0 ? Should be deg(R) = -∞, right ?

### ISSUE THREAD

**Issue by mathusanm6** [Yag000/algebre-II-notes#7]
Here is the highlighted version of the proof :

<img width="749" alt="SCR-20240118-lffs" src="https://github.com/Yag000/algebre-II-notes/assets/89030828/e694d663-903c-4dfa-b19b-26d795806d26">

This issue is to be sure if it's really a problem or just me not understanding 💀 !

**Comment by GabinDDL** [comment]
you're right, I'll correct it

**Comment by Yag000** [comment]
Fixed
